
# model-api
server:
  port: 8001

spring:
  application:
    name: model-api
  cloud:
    nacos:
      discovery:
        server-addr: 103.45.105.132:8848

feign:
  sentinel:
    enabled: true

swagger:
  title: Sprica-Model
  description: Sprica-Model后端Api文档，方便前端调用
  author: wtrue
  self-url: www.meidanlong.com
  email: meidanlong@qq.com
  version: 1.0.0-SNAPSHOT
  web: www.sprica.cn

