
# model-api
server:
  port: 8000

spring:
  application:
    name: model-api
  cloud:
    nacos:
      discovery:
        server-addr: 103.45.105.132:8848

feign:
  sentinel:
    enabled: true
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
        requestInterceptors:
          - com.wtrue.sprica.service.api.feign.interceptor.TokenRelayRequestInterceptor
    httpclient:
      # 让feign使用apache httpclient做请求；而不是默认的urlconnection
      enabled: true
      # feign的最大连接数
      max-connections: 200
      # feign单个路径的最大连接数
      max-connections-per-route: 50

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


