
# model-api
server:
  port: 8000

spring:
  application:
    name: model-api
  cloud:
    nacos:
      discovery:
        server-addr: 103.45.105.132:8848

feign:
  sentinel:
    enabled: true
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
        requestInterceptors:
          - com.wtrue.sprica.service.feign.interceptor.TokenRelayRequestInterceptor
    httpclient:
      # 让feign使用apache httpclient做请求；而不是默认的urlconnection
      enabled: true
      # feign的最大连接数
      max-connections: 200
      # feign单个路径的最大连接数
      max-connections-per-route: 50

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# Swagger
swagger:
  title: Sprica-Model-API
  description: Sprica-Model后端Api文档，方便前端调用
  author: wtrue
  self-url: www.meidanlong.com
  email: meidanlong@qq.com
  version: 1.0.0-SNAPSHOT
  web: www.sprica.cn


