
# model
server:
  port: 8001

spring:
  application:
    name: model-service
  datasource:
    url: jdbc:mysql://103.45.105.132:3306/model
    hikari:
      username: root
      password: root123
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 103.45.105.132:8848
