
# model
server:
  port: 8001

spring:
  application:
    name: sprica-backend-service
  datasource:
    url: jdbc:mysql://ip:host/sprica
    hikari:
      username: username
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 103.45.105.132:8848



# Swagger
swagger:
  title: Sprica-Backend
  description: Sprica-Backend后端服务文档，方便前端调用
  author: wtrue
  self-url: www.meidanlong.com
  email: meidanlong@qq.com
  version: 1.0.0-SNAPSHOT
  web: www.sprica.cn
